# Generated by Django 4.2 on 2023-04-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_remove_privatechat_connected_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='msj',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='username',
        ),
    ]
