# Generated by Django 4.2 on 2023-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Like'), ('C', 'Comment'), ('F', 'Follow'), ('RT', 'Retweet'), ('M', 'Message')], default=None, max_length=2),
        ),
    ]
