# Generated by Django 4.2 on 2023-04-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_alter_comment_tweet'),
        ('notifications', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
